// <auto-generated />
using System;
using EverydayChain.Hub.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EverydayChain.Hub.Infrastructure.Migrations
{
    [DbContext(typeof(HubDbContext))]
    partial class HubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EverydayChain.Hub.Domain.Aggregates.BusinessTaskAggregate.BusinessTaskEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ActualChuteCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Barcode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("BusinessKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreatedTimeLocal")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("DroppedAtLocal")
                        .HasColumnType("datetime2");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("FeedbackStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FeedbackTimeLocal")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("HeightMm")
                        .HasColumnType("decimal(18,3)");

                    b.Property<bool>("IsException")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeedbackReported")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRecirculated")
                        .HasColumnType("bit");

                    b.Property<decimal?>("LengthMm")
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("ScanCount")
                        .HasColumnType("int");

                    b.Property<int>("ScanRetryCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ScannedAtLocal")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourceTableCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("SourceType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TargetChuteCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TaskCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("UpdatedTimeLocal")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("VolumeMm3")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("WaveCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("WaveRemark")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal?>("WeightGram")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("WidthMm")
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("ActualChuteCode");

                    b.HasIndex("Barcode");

                    b.HasIndex("CreatedTimeLocal");

                    b.HasIndex("FeedbackStatus");

                    b.HasIndex("FeedbackTimeLocal");

                    b.HasIndex("IsException");

                    b.HasIndex("IsFeedbackReported");

                    b.HasIndex("IsRecirculated");

                    b.HasIndex("SourceType");

                    b.HasIndex("Status");

                    b.HasIndex("TargetChuteCode");

                    b.HasIndex("TaskCode")
                        .IsUnique();

                    b.HasIndex("WaveCode");

                    b.HasIndex("Barcode", "CreatedTimeLocal");

                    b.HasIndex("CreatedTimeLocal", "Id");

                    b.HasIndex("FeedbackStatus", "CreatedTimeLocal");

                    b.HasIndex("WaveCode", "CreatedTimeLocal");

                    b.HasIndex("FeedbackStatus", "IsFeedbackReported", "FeedbackTimeLocal");

                    b.HasIndex("CreatedTimeLocal", "WaveCode", "TargetChuteCode", "ActualChuteCode");

                    b.HasIndex("CreatedTimeLocal", "SourceType", "Status", "IsException", "IsRecirculated");

                    b.ToTable("business_tasks", "dbo");
                });

            modelBuilder.Entity("EverydayChain.Hub.Domain.Aggregates.DropLogAggregate.DropLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ActualChuteCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Barcode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long?>("BusinessTaskId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedTimeLocal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DropTimeLocal")
                        .HasColumnType("datetime2");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<string>("TaskCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("ActualChuteCode");

                    b.HasIndex("Barcode");

                    b.HasIndex("BusinessTaskId");

                    b.HasIndex("DropTimeLocal");

                    b.HasIndex("TaskCode");

                    b.HasIndex("Barcode", "DropTimeLocal");

                    b.HasIndex("TaskCode", "DropTimeLocal");

                    b.ToTable("drop_logs", "dbo");
                });

            modelBuilder.Entity("EverydayChain.Hub.Domain.Aggregates.ScanLogAggregate.ScanLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long?>("BusinessTaskId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedTimeLocal")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsMatched")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ScanTimeLocal")
                        .HasColumnType("datetime2");

                    b.Property<string>("TaskCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("Barcode");

                    b.HasIndex("BusinessTaskId");

                    b.HasIndex("ScanTimeLocal");

                    b.HasIndex("TaskCode");

                    b.HasIndex("Barcode", "ScanTimeLocal");

                    b.HasIndex("TaskCode", "ScanTimeLocal");

                    b.ToTable("scan_logs", "dbo");
                });

            modelBuilder.Entity("EverydayChain.Hub.Domain.Aggregates.SortingTaskTraceAggregate.SortingTaskTraceEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BusinessNo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Payload")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("StationCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("BusinessNo");

                    b.HasIndex("CreatedAt");

                    b.ToTable("sorting_task_trace", "dbo");
                });

            modelBuilder.Entity("EverydayChain.Hub.Domain.Aggregates.SyncBatchAggregate.SyncBatchEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BatchId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("CompletedTimeLocal")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeleteCount")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<int>("InsertCount")
                        .HasColumnType("int");

                    b.Property<string>("ParentBatchId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("ReadCount")
                        .HasColumnType("int");

                    b.Property<int>("SkipCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartedTimeLocal")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TableCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("UpdateCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("WindowEndLocal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WindowStartLocal")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("BatchId")
                        .IsUnique();

                    b.HasIndex("Status", "CompletedTimeLocal");

                    b.HasIndex("TableCode", "Status", "CompletedTimeLocal");

                    b.ToTable("sync_batches", "dbo");
                });

            modelBuilder.Entity("EverydayChain.Hub.Domain.Aggregates.SyncChangeLogAggregate.SyncChangeLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AfterSnapshot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BatchId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("BeforeSnapshot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("ChangedTimeLocal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedTimeLocal")
                        .HasColumnType("datetime2");

                    b.Property<int>("OperationType")
                        .HasColumnType("int");

                    b.Property<string>("ParentBatchId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TableCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("BatchId");

                    b.HasIndex("TableCode", "ChangedTimeLocal");

                    b.ToTable("sync_change_logs", "dbo");
                });

            modelBuilder.Entity("EverydayChain.Hub.Domain.Aggregates.SyncDeletionLogAggregate.SyncDeletionLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BatchId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("BusinessKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreatedTimeLocal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedTimeLocal")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeletionPolicy")
                        .HasColumnType("int");

                    b.Property<bool>("Executed")
                        .HasColumnType("bit");

                    b.Property<string>("ParentBatchId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SourceEvidence")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("TableCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("BatchId");

                    b.HasIndex("TableCode", "DeletedTimeLocal");

                    b.ToTable("sync_deletion_logs", "dbo");
                });

            modelBuilder.Entity("EverydayChain.Hub.Domain.Aggregates.WmsPickToWcsAggregate.WmsPickToWcsEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AddTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("ADDTIME");

                    b.Property<string>("BoxBarcode")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("SKUID");

                    b.Property<int?>("ChuteNo")
                        .HasColumnType("int")
                        .HasColumnName("SEQNO");

                    b.Property<DateTime?>("CloseTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("CLOSETIME");

                    b.Property<string>("ConsigneeId")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("CONSIGNEEID");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DESCR");

                    b.Property<string>("DocumentNo")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("DOCNO");

                    b.Property<DateTime?>("EditTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("EDITTIME");

                    b.Property<string>("Flag")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("FLAG");

                    b.Property<decimal?>("GrossWeightGram")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("GROSSWEIGHT");

                    b.Property<decimal?>("HeightCm")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("HIGH");

                    b.Property<decimal?>("LengthCm")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("LENGTH");

                    b.Property<string>("LocationCode")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("LOCATION");

                    b.Property<decimal?>("MinUnitQuantity")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("SKUQTY1");

                    b.Property<DateTime?>("OpenTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("OPENTIME");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("QTY");

                    b.Property<int?>("ScanCount")
                        .HasColumnType("int")
                        .HasColumnName("SCANCOUNT");

                    b.Property<string>("SequenceNo")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("ALLNUM");

                    b.Property<string>("SequenceNo1")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("ALLNUM1");

                    b.Property<string>("SkuCode")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("SKU");

                    b.Property<string>("SkuQuantityText")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("SKUQTY");

                    b.Property<string>("SkuSequence")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("SKUSEQ");

                    b.Property<string>("Status")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("STATUS");

                    b.Property<string>("StoreName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("MENDIAN");

                    b.Property<string>("TaskProcess")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("TASKPROCESS");

                    b.Property<string>("UniqueId")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("R_SYSID");

                    b.Property<decimal?>("VolumeCubicCm")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("CUBE");

                    b.Property<string>("WaveNo")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("WAVENO");

                    b.Property<string>("WcsNo")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("WCSNO");

                    b.Property<decimal?>("WidthCm")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("WIDTH");

                    b.Property<string>("ZjFlag")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("ZJFLAG");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("AddTime");

                    b.HasIndex("UniqueId");

                    b.HasIndex("DocumentNo", "AddTime");

                    b.ToTable("IDX_PICKTOWCS2", "dbo");
                });

            modelBuilder.Entity("EverydayChain.Hub.Domain.Aggregates.WmsSplitPickToLightCartonAggregate.WmsSplitPickToLightCartonEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AddTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("ADDTIME");

                    b.Property<string>("AddedByUserId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ADDWHO");

                    b.Property<string>("AdditionalFlag")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("ADDITIONAL");

                    b.Property<string>("CartonNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("CARTONNO");

                    b.Property<int?>("ChuteNo")
                        .HasColumnType("int")
                        .HasColumnName("SEQNO");

                    b.Property<DateTime?>("CloseTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("CLOSETIME");

                    b.Property<string>("ConsigneeId")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("CONSIGNEEID");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DESCR");

                    b.Property<string>("DocumentNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("DOCNO");

                    b.Property<decimal?>("GrossWeightGram")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("GROSSWEIGHT");

                    b.Property<decimal?>("HeightCm")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("HIGH");

                    b.Property<decimal?>("LengthCm")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("LENGTH");

                    b.Property<DateTime?>("OpenTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("OPENTIME");

                    b.Property<int?>("ScanCount")
                        .HasColumnType("int")
                        .HasColumnName("SCANCOUNT");

                    b.Property<string>("SortationLocationCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("SORTATIONLOCATION");

                    b.Property<string>("Status")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("STATUS");

                    b.Property<string>("StopCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("STOP");

                    b.Property<string>("StoreId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("STOREID");

                    b.Property<string>("StoreName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("MENDIAN");

                    b.Property<string>("TaskProcess")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("TASKPROCESS");

                    b.Property<string>("UseFlag")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("USEFLAG");

                    b.Property<decimal?>("VolumeCubicCm")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("CUBE");

                    b.Property<string>("WarehouseId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("WAREHOUSEID");

                    b.Property<string>("WaveNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("WAVENO");

                    b.Property<string>("WcsNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("WCSNO");

                    b.Property<decimal?>("WidthCm")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("WIDTH");

                    b.Property<string>("WorkingAreaCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("WORKINGAREA");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("AddTime");

                    b.HasIndex("CartonNo")
                        .IsUnique();

                    b.ToTable("IDX_PICKTOLIGHT_CARTON1", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
