// <auto-generated />
using System;
using EverydayChain.Hub.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EverydayChain.Hub.Infrastructure.Migrations
{
    [DbContext(typeof(HubDbContext))]
    partial class HubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EverydayChain.Hub.Domain.Aggregates.BusinessTaskAggregate.BusinessTaskEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ActualChuteCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Barcode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("BusinessKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreatedTimeLocal")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("DroppedAtLocal")
                        .HasColumnType("datetime2");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("FeedbackStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FeedbackTimeLocal")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("HeightMm")
                        .HasColumnType("decimal(18,3)");

                    b.Property<bool>("IsException")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeedbackReported")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRecirculated")
                        .HasColumnType("bit");

                    b.Property<decimal?>("LengthMm")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("NormalizedBarcode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("NormalizedWaveCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("OrderId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PickLocation")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ProductCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ResolvedDockCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("ScanCount")
                        .HasColumnType("int");

                    b.Property<int>("ScanRetryCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ScannedAtLocal")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourceTableCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("SourceType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StoreId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("StoreName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("TargetChuteCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TaskCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("UpdatedTimeLocal")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("VolumeMm3")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("WaveCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("WaveRemark")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal?>("WeightGram")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("WidthMm")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("WorkingArea")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("ActualChuteCode");

                    b.HasIndex("Barcode");

                    b.HasIndex("CreatedTimeLocal");

                    b.HasIndex("DroppedAtLocal");

                    b.HasIndex("FeedbackStatus");

                    b.HasIndex("FeedbackTimeLocal");

                    b.HasIndex("IsException");

                    b.HasIndex("IsFeedbackReported");

                    b.HasIndex("NormalizedBarcode");

                    b.HasIndex("NormalizedWaveCode");

                    b.HasIndex("ResolvedDockCode");

                    b.HasIndex("ScannedAtLocal");

                    b.HasIndex("SourceType");

                    b.HasIndex("Status");

                    b.HasIndex("TargetChuteCode");

                    b.HasIndex("TaskCode")
                        .IsUnique();

                    b.HasIndex("UpdatedTimeLocal");

                    b.HasIndex("WaveCode");

                    b.HasIndex("WorkingArea");

                    b.HasIndex("Barcode", "CreatedTimeLocal");

                    b.HasIndex("CreatedTimeLocal", "Id");

                    b.HasIndex("CreatedTimeLocal", "NormalizedWaveCode");

                    b.HasIndex("CreatedTimeLocal", "ResolvedDockCode");

                    b.HasIndex("FeedbackStatus", "CreatedTimeLocal");

                    b.HasIndex("NormalizedBarcode", "CreatedTimeLocal");

                    b.HasIndex("NormalizedWaveCode", "CreatedTimeLocal");

                    b.HasIndex("NormalizedWaveCode", "UpdatedTimeLocal");

                    b.HasIndex("TargetChuteCode", "CreatedTimeLocal");

                    b.HasIndex("ActualChuteCode", "CreatedTimeLocal");

                    b.HasIndex("ResolvedDockCode", "CreatedTimeLocal");

                    b.HasIndex("SourceTableCode", "BusinessKey")
                        .IsUnique();

                    b.HasIndex("WaveCode", "CreatedTimeLocal");

                    b.HasIndex("CreatedTimeLocal", "ScannedAtLocal", "Id");

                    b.HasIndex("CreatedTimeLocal", "NormalizedWaveCode", "ResolvedDockCode");

                    b.HasIndex("CreatedTimeLocal", "Status", "SourceType");

                    b.HasIndex("FeedbackStatus", "IsFeedbackReported", "FeedbackTimeLocal");

                    b.HasIndex("NormalizedWaveCode", "SourceType", "WorkingArea");

                    b.HasIndex("CreatedTimeLocal", "SourceType", "Status", "IsException", "ResolvedDockCode");

                    b.ToTable("business_tasks", "dbo");
                });

            modelBuilder.Entity("EverydayChain.Hub.Domain.Aggregates.DashboardSnapshotAggregate.DashboardScanSnapshotEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("BucketStartLocal")
                        .HasColumnType("datetime2");

                    b.Property<int>("MatchedScanCount")
                        .HasColumnType("int");

                    b.Property<int>("TotalScanCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("BucketStartLocal")
                        .IsUnique();

                    b.ToTable("dashboard_scan_snapshots", "dbo");
                });

            modelBuilder.Entity("EverydayChain.Hub.Domain.Aggregates.DashboardSnapshotAggregate.DashboardCurrentWaveSnapshotEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("BucketStartLocal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ScannedAtLocal")
                        .HasColumnType("datetime2");

                    b.Property<string>("WaveCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("WaveRemark")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("BucketStartLocal")
                        .IsUnique();

                    b.HasIndex("BucketStartLocal", "ScannedAtLocal");

                    b.ToTable("dashboard_current_wave_snapshots", "dbo");
                });

            modelBuilder.Entity("EverydayChain.Hub.Domain.Aggregates.DashboardSnapshotAggregate.DashboardSnapshotStateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedNever()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CoverageEndLocal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CoverageStartLocal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastRefreshTimeLocal")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.ToTable("dashboard_snapshot_states", "dbo");
                });

            modelBuilder.Entity("EverydayChain.Hub.Domain.Aggregates.DashboardSnapshotAggregate.DashboardTaskSnapshotEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("BucketStartLocal")
                        .HasColumnType("datetime2");

                    b.Property<int>("CompletedFeedbackCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("EarliestCreatedTimeLocal")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExceptionCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("LatestUpdatedTimeLocal")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecirculatedCount")
                        .HasColumnType("int");

                    b.Property<int>("RequiredFeedbackCount")
                        .HasColumnType("int");

                    b.Property<string>("ResolvedDockCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("ScannedCount")
                        .HasColumnType("int");

                    b.Property<int>("SourceType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TotalCount")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalVolumeMm3")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("TotalWeightGram")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("WaveCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("WaveRemark")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("WorkingArea")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("BucketStartLocal");

                    b.HasIndex("BucketStartLocal", "ResolvedDockCode");

                    b.HasIndex("BucketStartLocal", "WaveCode");

                    b.HasIndex("BucketStartLocal", "WaveCode", "ResolvedDockCode");

                    b.HasIndex("BucketStartLocal", "WaveCode", "SourceType", "Status");

                    b.HasIndex("BucketStartLocal", "WaveCode", "WorkingArea", "SourceType", "Status");

                    b.ToTable("dashboard_task_snapshots", "dbo");
                });

            modelBuilder.Entity("EverydayChain.Hub.Domain.Aggregates.RuntimeLeaseAggregate.RuntimeLeaseEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("AcquiredTimeLocal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtLocal")
                        .HasColumnType("datetime2");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("ExpiresAtLocal");

                    b.ToTable("runtime_leases", "dbo");
                });

            modelBuilder.Entity("EverydayChain.Hub.Domain.Aggregates.AuditLogs.WaveCleanupAuditLogEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("CleanedCount")
                        .HasColumnType("int");

                    b.Property<string>("ClientIp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("CompletedTimeLocal")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExecutionStage")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("IdentifiedCount")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("RequestPath")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("RequestedTimeLocal")
                        .HasColumnType("datetime2");

                    b.Property<string>("TargetStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("WaveCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("ExecutionStage");

                    b.HasIndex("RequestedTimeLocal");

                    b.HasIndex("WaveCode", "RequestedTimeLocal");

                    b.ToTable("wave_cleanup_audit_logs", "dbo");
                });

            modelBuilder.Entity("EverydayChain.Hub.Domain.Aggregates.AuditLogs.RetentionCleanupAuditLogEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("AllowDelete")
                        .HasColumnType("bit");

                    b.Property<string>("BatchId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("CandidateCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedTimeLocal")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeletedCount")
                        .HasColumnType("int");

                    b.Property<string>("ExecutionStage")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("InstanceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsDryRun")
                        .HasColumnType("bit");

                    b.Property<int>("KeepMonths")
                        .HasColumnType("int");

                    b.Property<string>("LogicalTableName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("RetentionMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("ScannedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedTimeLocal")
                        .HasColumnType("datetime2");

                    b.Property<string>("TargetCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("ThresholdTimeLocal")
                        .HasColumnType("datetime2");

                    b.Property<string>("TimeColumnName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("ExecutionStage");

                    b.HasIndex("StartedTimeLocal");

                    b.HasIndex("BatchId", "StartedTimeLocal");

                    b.HasIndex("LogicalTableName", "StartedTimeLocal");

                    b.ToTable("retention_cleanup_audit_logs", "dbo");
                });

            modelBuilder.Entity("EverydayChain.Hub.Domain.Aggregates.DropLogAggregate.DropLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ActualChuteCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Barcode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long?>("BusinessTaskId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedTimeLocal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DropTimeLocal")
                        .HasColumnType("datetime2");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<string>("TaskCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("ActualChuteCode");

                    b.HasIndex("Barcode");

                    b.HasIndex("BusinessTaskId");

                    b.HasIndex("CreatedTimeLocal");

                    b.HasIndex("DropTimeLocal");

                    b.HasIndex("IsSuccess");

                    b.HasIndex("TaskCode");

                    b.HasIndex("Barcode", "DropTimeLocal");

                    b.HasIndex("CreatedTimeLocal", "DropTimeLocal");

                    b.HasIndex("CreatedTimeLocal", "TaskCode");

                    b.HasIndex("TaskCode", "DropTimeLocal");

                    b.ToTable("drop_logs", "dbo");
                });

            modelBuilder.Entity("EverydayChain.Hub.Domain.Aggregates.ScanLogAggregate.ScanLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long?>("BusinessTaskId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedTimeLocal")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsMatched")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ScanTimeLocal")
                        .HasColumnType("datetime2");

                    b.Property<string>("TaskCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("Barcode");

                    b.HasIndex("BusinessTaskId");

                    b.HasIndex("CreatedTimeLocal");

                    b.HasIndex("DeviceCode");

                    b.HasIndex("ScanTimeLocal");

                    b.HasIndex("TaskCode");

                    b.HasIndex("Barcode", "ScanTimeLocal");

                    b.HasIndex("CreatedTimeLocal", "ScanTimeLocal");

                    b.HasIndex("CreatedTimeLocal", "TaskCode");

                    b.HasIndex("DeviceCode", "ScanTimeLocal");

                    b.HasIndex("ScanTimeLocal", "Id");

                    b.HasIndex("TaskCode", "ScanTimeLocal");

                    b.ToTable("scan_logs", "dbo");
                });

            modelBuilder.Entity("EverydayChain.Hub.Domain.Aggregates.SortingTaskTraceAggregate.SortingTaskTraceEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BusinessNo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Payload")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("StationCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("BusinessNo");

                    b.HasIndex("CreatedAt");

                    b.ToTable("sorting_task_trace", "dbo");
                });

            modelBuilder.Entity("EverydayChain.Hub.Domain.Aggregates.SyncBatchAggregate.SyncBatchEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BatchId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("CompletedTimeLocal")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeleteCount")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<int>("InsertCount")
                        .HasColumnType("int");

                    b.Property<string>("ParentBatchId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("ReadCount")
                        .HasColumnType("int");

                    b.Property<int>("SkipCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartedTimeLocal")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TableCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("UpdateCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("WindowEndLocal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WindowStartLocal")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("BatchId")
                        .IsUnique();

                    b.HasIndex("Status", "CompletedTimeLocal");

                    b.HasIndex("TableCode", "Status", "CompletedTimeLocal");

                    b.ToTable("sync_batches", "dbo");
                });

            modelBuilder.Entity("EverydayChain.Hub.Domain.Aggregates.SyncChangeLogAggregate.SyncChangeLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AfterSnapshot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BatchId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("BeforeSnapshot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("ChangedTimeLocal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedTimeLocal")
                        .HasColumnType("datetime2");

                    b.Property<int>("OperationType")
                        .HasColumnType("int");

                    b.Property<string>("ParentBatchId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TableCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("BatchId");

                    b.HasIndex("TableCode", "ChangedTimeLocal");

                    b.ToTable("sync_change_logs", "dbo");
                });

            modelBuilder.Entity("EverydayChain.Hub.Domain.Aggregates.SyncDeletionLogAggregate.SyncDeletionLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BatchId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("BusinessKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreatedTimeLocal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedTimeLocal")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeletionPolicy")
                        .HasColumnType("int");

                    b.Property<bool>("Executed")
                        .HasColumnType("bit");

                    b.Property<string>("ParentBatchId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SourceEvidence")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("TableCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("BatchId");

                    b.HasIndex("TableCode", "DeletedTimeLocal");

                    b.ToTable("sync_deletion_logs", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
